### ISSUE TITLE
Local MQTT Broker

### ISSUE THREAD

**Issue by mikihacia** [2pk03/bacnet-mqtt-gateway#23]
Hi there.

It's a brilliant piece of work you've done here! 

Would it be possible to get it working with a local MQTT broker (i.e. mosquito) as they don't normally require a certificates and gateway IDs?

Regards,
Mick,

**Comment by alteoxCOM** [comment]
+1

**Comment by eov-oleg** [comment]
+1

**Comment by andreapx** [comment]
Yes, please please please!!!!

**Comment by mlavelle42** [comment]
Agreed to use a local MQTT broker like Mosquitto.

**Comment by Bagunda** [comment]
+1.
How to join a local broker with a login and password?

**Comment by 2pk03** [comment]
Hey sorry I missed this one here. Yes a local broker would be a feature, let me think about a great way without having too much trouble.

**Comment by 2pk03** [comment]
Darn I forgot this again! That should work:

`{
    "mqtt": {
        "gatewayId": "YOUR DEVICE ID",
        "host": "localhost",
        "port": MQTT Port,
         },
    "bacnet": {
        "configFolder": "./devices/"
    },
    "httpServer": {
        "enabled": true,
        "port": 8082
    }
}`

Mosquitto uses localhost per default, to allow connections from other servers the configuration needs to be tuned:

`allow_anonymous true
listener 1883`
